### ISSUE TITLE
"Error loading extension" error in Ubuntu 17.10 64 bit

### ISSUE THREAD

**Issue by contactvinoth89** [The-Panacea-Projects/Gnomenu#77]
I have installed Gnomenu in Ubuntu 17.10 64 bit. But i am not able to enable it. I could see an error message "Error loading extension"

**Comment by passingthru67** [comment]
That's not much to go on. Can you check the output of journalctl for errors related to gnomenu and let us know what you find?

**Comment by lexruee** [comment]
@contactvinoth89  @passingthru67 
The main problem is that Ubuntu 17.10 ships IMOH a broken GNOME desktop. In brief, I guess the problem is that the `gir1.2-gmenu-3.0` dependency is missing in Ubuntu 17.10. Moreover, the gnome-session must be used instead of the ubuntu-sesseion.

So, installing `gir1.2-gmenu-3.0` could probably fix the issue:

```
apt install  gir1.2-gmenu-3.0
```

**Comment by contactvinoth89** [comment]
Installing gir1.2-gmenu-3.0 solved my problem. I guess what @lexruee said about Ubuntu 17.10 Gnome. It has loads of bugs. Even my mouse movement is not consistent. Thanks for helping out.
