### ISSUE TITLE
Script Files 

### ISSUE THREAD

**Issue by AWeinb** [The-Panacea-Projects/Gnomenu#8]
Hey,

wouldn't it be nice to structure the script files a little bit more. I thought of putting the js-files except for the boilerplate files in a special folder. Also I saw that most of the program logic is written inside the main js-files. Is it possible to split it in more files?

Sincerely,
AxP

**Comment by passingthru67** [comment]
Hi  @AWeinb
Just wanted to let you know I haven't forgotten about you. I'm working as a developer with The-Panacea-Projects and hope to incorporate some (or all) of your suggestions. I'll have to study the changes some more before I can comment any further.

Thanks again for your interest in this project.

**Comment by AWeinb** [comment]
Very good, no problem! :penguin:

**Comment by The-Panacea-Projects** [comment]
Hi AxP how goes things, hoping all is well. I am another Develper with 
this project and I am thinking if time allowed, would you consider 
helping to implement a couple of new features in Gno-Menu? I realise we 
have yet to properly assess or implement what you have already done 
thus far, but this is due to workload pressures unrelated to this 
project more so than a lack of will or interest. We would really like 
to keep things moving along where possible. Attached is a list of stuff 
we would like to see implimented. Let us know what you think and 
suggestions are also welcome.

On Mon, Jan 12, 2015 at 3:47 AM, AxP <notifications@github.com> wrote:
> Very good, no problem!
> 
> —
> Reply to this email directly or view it on GitHub.
> 
=
Gno­Menu 
======== 
 
Features: 
­­­­­­­­­­­­ 
 
1) Incorporate pagination on the application grid view to be more consistent with the current 
Gnome Shell apps view. 
 
2) Enhance the application list/grid view by separating results into categories. This is 
especially beneficial for search results. At the moment, recent, bookmarks, and applications 
from a search are lumped together in the resulting view. 
 
3) Change the Favorites button label to display Apps/Workspaces alternately. Add Favorites and possibly Places to categories.
 
4) Provide an auto­scroll function to display hidden application categories. This can be done 
using the upper and lower sections of the scrollview box. Hovering over the area will cause the categories to scroll up/down.
 
5) Provide an auto­scroll function to display hidden icons on the shortcuts panel in similar 
fashion to the application categories (see above). 
 
6) Merge apps view control ( list/ grid ) into a single button. 
 
7) Incorporate web search functionality. 
 
8) Change position of menu button to reduce accidental triggering of default appmenu.   
 
9) Add option to remove labels from panel buttons. 
 
10) Add option to move panel clock to the right. 
 
11) Add the app­well­app.running > overview class to distinguish active/running apps. 
=

**Comment by AWeinb** [comment]
Sounds good to me. But at the moment I can not help much. It's a little bit busy here, atm. But maybe soon.

**Comment by The-Panacea-Projects** [comment]
It's good having you onboard. Lack of spare time is our achilles heel 
and the main reason why more has yet to be accomplished, so  we do look 
forward to your assistance in anyway time does allow.

BTW  The list isn't chronological and given the time constraints 
tackling the simpler mods first might work out better.

On Tue, Jan 27, 2015 at 5:01 AM, AxP <notifications@github.com> wrote:
> Sounds good to me. But at the moment I can not help much. It's a 
> little bit busy here, atm. But maybe soon.
> 
> —
> Reply to this email directly or view it on GitHub.
> 
=
